# Generated by Django 5.0.6 on 2024-10-12 01:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, unique=True, verbose_name='IMEI')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('falla_reportada', models.TextField(verbose_name='Descripción de la falla')),
                ('prueba_carga', models.CharField(choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No Funciona'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=11)),
                ('prueba_camara', models.CharField(choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No Funciona'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=11)),
                ('prueba_microfono', models.CharField(choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No Funciona'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=11)),
                ('costo_reparacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total de Reparación')),
                ('abono', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Abono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
