# Generated by Django 5.0.6 on 2024-10-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenreparacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='numero_orden',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
