# Generated by Django 5.0.6 on 2024-10-09 01:16

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=productos.models.get_default_proveedor, on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor'),
        ),
    ]
